config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
      sessions: 'authentication/sessions'
  }
  mount V2::Root => '/'
  devise_scope :user do
    authenticated :user do
      root 'main#home', as: :authenticated_root
      get 'calendarApp/', to: 'main#calendarApp' #ruta para el componente CalendarApp
      #Api Routes
      namespace :api do
        namespace :v1 do
          resources :users, only: [:index,:show, :create, :destroy, :update] # usuarios del sistema
          get 'list_shifts', to: 'list_shift#index'
          get 'list_departments', to: 'data_sets#index'
          get 'list_departments/:id', to: 'data_sets#show'
          get 'list_benefits', to: 'benefits#index'
          get 'list_benefits/:id', to: 'benefits#show'

        end
      end
      # web routes
      namespace :web do
        resources :contracts, :benefits, :departments, :shifts, :employees, :users, :areas, :calendars, :holidays
        get 'calendar_programmed_vs_real', to: 'calendar_trace#index'
        get 'kpi_productivity', to: 'calendar_trace#assistance'
        get 'update_holidays', to: 'holidays#refill', via: [:post]
      end
    end

  #Api Routes
  namespace :api do
      devise_for :users
    namespace :v1 do
      resources :calendars , param: :data
      resources :users, only: [:index,:show, :create, :destroy, :update] # usuarios del sistema
      get 'list_shifts', to: 'list_shift#index'
      get 'list_shifts/:time', to: 'list_shift#search_shift_type'
      get 'list_departments', to: 'data_sets#departments'
      get 'list_areas', to: 'data_sets#index'
      get 'list_areas/:id', to: 'data_sets#show'
      get 'list_benefits', to: 'benefits#index'
      get 'list_contracts', to: 'contracts#index'
      get 'list_benefits/:id', to: 'benefits#show'
      get 'List_calendars_code/:code', to: 'calendars#calendar_code'
      get 'list_calendar_logs', to: 'calendar_logs#index'
      get 'list_calendar_logs/:code', to: 'calendar_logs#show'
      get 'list_calendar_logs_dep/:department_id', to: 'calendar_logs#logs_dep'
      get 'list_calendar_logs_date/:date', to: 'calendar_logs#logs_date'
      get 'list_holidays', to: 'holidays#index'
      get 'list_holidays_year/:year', to: 'holidays#list_year'
      get 'list_holidays_month_year/:month/:year', to: 'holidays#list_month_year'
    end
  end
end

  # ========== Kit coding ========== #

  root 'main#home'
  get '*path' => 'main#err'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  add_breadcrumb 'Home', :root_path
  def home
    @path = "Dashboard"
  end
  def calendarApp
    add_breadcrumb "Asignaciones", '/calendarApp'
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/dash_board/_admin_main.html.haml
= render partial: 'layouts/menutop'
.ui.container
  - if !notice.nil?
    = render partial: '/layouts/notice'
  %h1.ui.icon.header #{fa_icon "gear"} Dashboard
  .ui.two.column.doubling.stackable.grid.container
    .column
      %h4.ui.horizontal.divider.header.tone Administración
      .panel-element
        = link_to '<i class="fa fa-star-half-o" aria-hidden="true"></i> Beneficios'.html_safe, web_benefits_path

      .panel-element
        = link_to '<i class="fa fa-file-text-o" aria-hidden="true"></i> Contratos'.html_safe, web_contracts_path

      .panel-element
        = link_to '<i class="fa fa-history" aria-hidden="true"></i> Turnos'.html_safe, web_shifts_path
      .panel-element
        = link_to '<i class="sun icon" aria-hidden="true"></i> Feriados'.html_safe, web_holidays_path
    .column
      %h4.ui.horizontal.divider.header.tone Organización
      .panel-element
        = link_to '<i class="fa fa-sitemap" aria-hidden="true"></i> Departamentos'.html_safe ,web_departments_path

      .panel-element
        =link_to '<i class="fa fa-users" aria-hidden="true"></i> Empleados'.html_safe,  web_employees_path

  .ui.two.column.doubling.stackable.grid.container
    .column
      %h4.ui.horizontal.divider.header.tone Horarios
      .panel-element
        = link_to '<i class="calendar icon" aria-hidden="true"></i> Asignación'.html_safe ,'/calendarApp/'

      .panel-element
        =link_to '<i class="checked calendar icon" aria-hidden="true"></i> Seguimiento'.html_safe,  web_calendar_programmed_vs_real_path

      .panel-element
        =link_to '<i class="download icon" aria-hidden="true"></i> Descargas'.html_safe, web_calendars_path

app/views/main/dash_board/_operator.html.haml
= render partial: 'layouts/menutop'
.ui.container
  - if !notice.nil?
    = render partial: '/layouts/notice'
  %h1.ui.icon.header #{fa_icon "gear"} Dashboard
  .ui.two.column.doubling.stackable.grid.container
    .column
      %h4.ui.horizontal.divider.header.tone Empleados y tuernos
      .panel-element
        = link_to '<i class="fa fa-history" aria-hidden="true"></i> Turnos'.html_safe, web_shifts_path
      .panel-element
        =link_to '<i class="fa fa-users" aria-hidden="true"></i> Empleados'.html_safe,  web_employees_path

    .column
      %h4.ui.horizontal.divider.header.tone Horarios
      .panel-element
        = link_to '<i class="calendar icon" aria-hidden="true"></i> Asignación'.html_safe ,'/calendarApp/'

      .panel-element
        =link_to '<i class="checked calendar icon" aria-hidden="true"></i> Seguimiento'.html_safe,  web_calendar_programmed_vs_real_path

      .panel-element
        =link_to '<i class="download icon" aria-hidden="true"></i> Descargas'.html_safe, web_calendars_path