config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
      sessions: 'authentication/sessions'
  }
  mount V2::Root => '/'
  devise_scope :user do
    authenticated :user do
      root 'main#home', as: :authenticated_root
      get 'calendarApp/', to: 'main#calendarApp' #ruta para el componente CalendarApp
      #Api Routes
      namespace :api do
        namespace :v1 do
          resources :users, only: [:index,:show, :create, :destroy, :update] # usuarios del sistema
          get 'list_shifts', to: 'list_shift#index'
          get 'list_departments', to: 'data_sets#index'
          get 'list_departments/:id', to: 'data_sets#show'
          get 'list_benefits', to: 'benefits#index'
          get 'list_benefits/:id', to: 'benefits#show'

        end
      end
      # web routes
      namespace :web do
        resources :contracts, :benefits, :departments, :shifts, :employees, :users, :areas, :calendars, :holidays
        get 'calendar_programmed_vs_real', to: 'calendar_trace#index'
        get 'kpi_productivity', to: 'calendar_trace#assistance'
        get 'update_holidays', to: 'holidays#refill', via: [:post]
      end
    end

  #Api Routes
  namespace :api do
      devise_for :users
    namespace :v1 do
      resources :calendars , param: :data
      resources :users, only: [:index,:show, :create, :destroy, :update] # usuarios del sistema
      get 'list_shifts', to: 'list_shift#index'
      get 'list_shifts/:time', to: 'list_shift#search_shift_type'
      get 'list_departments', to: 'data_sets#departments'
      get 'list_areas', to: 'data_sets#index'
      get 'list_areas/:id', to: 'data_sets#show'
      get 'list_benefits', to: 'benefits#index'
      get 'list_contracts', to: 'contracts#index'
      get 'list_benefits/:id', to: 'benefits#show'
      get 'List_calendars_code/:code', to: 'calendars#calendar_code'
      get 'list_calendar_logs', to: 'calendar_logs#index'
      get 'list_calendar_logs/:code', to: 'calendar_logs#show'
      get 'list_calendar_logs_dep/:department_id', to: 'calendar_logs#logs_dep'
      get 'list_calendar_logs_date/:date', to: 'calendar_logs#logs_date'
      get 'list_holidays', to: 'holidays#index'
      get 'list_holidays_year/:year', to: 'holidays#list_year'
      get 'list_holidays_month_year/:month/:year', to: 'holidays#list_month_year'
    end
  end
end

  # ========== Kit coding ========== #

  root 'main#home'
  get '*path' => 'main#err'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/benefit.rb
# == Schema Information
#
# Table name: benefits
#
#  id          :integer          not null, primary key
#  cod         :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Benefit < ApplicationRecord
  has_many :employees
  validates :cod, presence: {:message => "Se requiere un código para el Beneficio."}
  validates :description, presence: {:message => "Se requiere una descripción del contrato."}, length: {minimum: 10, :message => "La descripción es demasaido corta."}
end

app/controllers/api/v1/benefits_controller.rb
class Api::V1::BenefitsController < ApplicationController
  before_action :set_benefit, only: [:index, :show]

  def index
    render json: @benefits = Benefit.all
  end

  def show
    if @benefit
      render json: @benefit
    else
      render json: {error: 'Beneficio no encontrado.', status: not_found}
    end
  end

  private
    def set_benefit
      @benefit = Benefit.find_by_id(params[:id])
    end

end

app/controllers/web/benefits_controller.rb
class Web::BenefitsController < ApplicationController
  before_action :set_benefit, only: [:show, :edit, :update, :destroy]
  before_action :validate_user
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Domingos Libres y otros beneficios", :web_benefits_path

  def index
    @benefits = Benefit.all.order(:id)
  end

  def show
    add_breadcrumb @benefit.cod, web_benefit_path
  end

  # GET /benefits/new
  def new
    @benefit = Benefit.new
    add_breadcrumb "Nuevo Beneficio", new_web_benefit_path
  end

  def edit
    add_breadcrumb "Edición #{@benefit.cod}"
  end

  def create
    @benefit = Benefit.new(benefit_params)
    if @benefit.save
      flash[:notice] = 'Beneficio creado correctamente'
      redirect_to action: :index
    else
      render 'new'
    end
  end

  def update
    if @benefit.update(benefit_params)
      redirect_to action: :index
      flash[:notice] = 'El Beneficio ha sido actualizado.'
    else
      render 'update'
    end
  end

  def destroy
    if @benefit.destroy!
      redirect_to action: :index
      flash[:notice] = 'El Beneficio ha sido Eliminado.'
    else
      render 'index'
      flash[:notice] = 'El Beneficio no se puede eliminar. Actualmente está asignado a uno o varios empleados'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_benefit
      @benefit = Benefit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def benefit_params
      params.require(:benefit).permit(:cod, :description)
    end

    def validate_user
      if current_user.nil? || current_user.operator?
        redirect_to new_user_session_path, notice: 'No Tiene permisos para esta seccion'
      end
    end
end

app/helpers/api/v1/benefits_helper.rb
module Api::V1::BenefitsHelper
end

app/helpers/web/benefits_helper.rb
module Web::BenefitsHelper
end

app/views/web/benefits/_form.html.haml
- if @benefit.errors.any?
  = # error handler
  .ui.error.mini.message
    %i.close.icon
    #error_explanation
    .header= "#{pluralize(@benefit.errors.count, "error")} prohibited this contract from being saved:"
    %ul.list
    - @benefit.errors.full_messages.each do |message|
      %li= message

= form_for(@benefit, url:url, method: method, html:{ class: 'ui form error'}) do |f|
  .field
    =text_field(:benefit, :cod, placeholder: 'Codigo beneficio')
  .field
    =text_area(:benefit, :description, placeholder: 'Descripción del beneficio')
  .actions
    = link_to 'Cancelar', web_benefits_path, class: 'ui button'
    -if @benefit.new_record?
      = f.submit 'Guardar', class: 'ui primary button'
    -else
      = f.submit 'Actualizar', class: 'ui primary button'

  = render partial: 'layouts/script_form_error'

app/views/web/benefits/edit.html.haml
= render partial: 'layouts/menutop'
= render partial: 'layouts/breadcrump'
- title "Editar #{@benefit.cod}"
.ui.text.container
  %h1 Modificar Beneficio #{@benefit.cod}
  = render partial: 'form', locals: {url: web_benefit_url(@benefit), method: 'put'}

app/views/web/benefits/index.html.haml
= render partial: 'layouts/menutop'
= render partial: 'layouts/breadcrump'
- title "Beneficios"
.ui.container
  - if !notice.nil?
    = render partial: 'layouts/notice'
  %h1 #{fa_icon "star-half-o"} Domingos Libres y otros beneficios
  %table.ui.green.celled.table
    %thead
      %tr
        %th.one.wide Código
        %th.one.wide Id
        %th.twelve.wide Descripción
        %th.one.wide Editar
        %th.one.wide Eliminar


    %tbody
      - @benefits.each do |benefit|
        %tr
          %td.selectable.positive= link_to benefit.cod, web_benefit_path(benefit)
          %td= benefit.id
          %td= benefit.description.to_s.truncate_words(25, omission: ' ...(continua)')
          %td.selectable.warning.center.aligned= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_web_benefit_path(benefit)
          %td.selectable.negative.center.aligned= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, web_benefit_path(benefit), method: :delete, data: { confirm: 'Are you sure?' }

  %br

  = link_to 'Crear nuevo Beneficio', new_web_benefit_path, class: 'ui primary button'

app/views/web/benefits/new.html.haml
= render partial: 'layouts/menutop'
= render partial: 'layouts/breadcrump'
- title "Nuevo Beneficio"
.ui.text.container
  %h1 Nuevo Beneficio
  = render partial: 'form', locals: {url: web_benefits_path, method: 'POST'}

app/views/web/benefits/show.html.haml
= render partial: 'layouts/menutop'
= render partial: 'layouts/breadcrump'
- title "Beneficio #{@benefit.cod}"
.ui.text.container
  %h2 Beneficio:  #{@benefit.cod}
  %p= @benefit.description

  = link_to 'Regresar', web_benefits_path, class: 'ui primary button'
  = link_to 'Editar', edit_web_benefit_path(@benefit),  class: 'ui button'