config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
      sessions: 'authentication/sessions'
  }
  mount V2::Root => '/'
  devise_scope :user do
    authenticated :user do
      root 'main#home', as: :authenticated_root
      get 'calendarApp/', to: 'main#calendarApp' #ruta para el componente CalendarApp
      #Api Routes
      namespace :api do
        namespace :v1 do
          resources :users, only: [:index,:show, :create, :destroy, :update] # usuarios del sistema
          get 'list_shifts', to: 'list_shift#index'
          get 'list_departments', to: 'data_sets#index'
          get 'list_departments/:id', to: 'data_sets#show'
          get 'list_benefits', to: 'benefits#index'
          get 'list_benefits/:id', to: 'benefits#show'

        end
      end
      # web routes
      namespace :web do
        resources :contracts, :benefits, :departments, :shifts, :employees, :users, :areas, :calendars, :holidays
        get 'calendar_programmed_vs_real', to: 'calendar_trace#index'
        get 'kpi_productivity', to: 'calendar_trace#assistance'
        get 'update_holidays', to: 'holidays#refill', via: [:post]
      end
    end

  #Api Routes
  namespace :api do
      devise_for :users
    namespace :v1 do
      resources :calendars , param: :data
      resources :users, only: [:index,:show, :create, :destroy, :update] # usuarios del sistema
      get 'list_shifts', to: 'list_shift#index'
      get 'list_shifts/:time', to: 'list_shift#search_shift_type'
      get 'list_departments', to: 'data_sets#departments'
      get 'list_areas', to: 'data_sets#index'
      get 'list_areas/:id', to: 'data_sets#show'
      get 'list_benefits', to: 'benefits#index'
      get 'list_contracts', to: 'contracts#index'
      get 'list_benefits/:id', to: 'benefits#show'
      get 'List_calendars_code/:code', to: 'calendars#calendar_code'
      get 'list_calendar_logs', to: 'calendar_logs#index'
      get 'list_calendar_logs/:code', to: 'calendar_logs#show'
      get 'list_calendar_logs_dep/:department_id', to: 'calendar_logs#logs_dep'
      get 'list_calendar_logs_date/:date', to: 'calendar_logs#logs_date'
      get 'list_holidays', to: 'holidays#index'
      get 'list_holidays_year/:year', to: 'holidays#list_year'
      get 'list_holidays_month_year/:month/:year', to: 'holidays#list_month_year'
    end
  end
end

  # ========== Kit coding ========== #

  root 'main#home'
  get '*path' => 'main#err'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/area.rb
# == Schema Information
#
# Table name: areas
#
#  id            :integer          not null, primary key
#  name          :string
#  description   :text
#  department_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_areas_on_department_id  (department_id)
#
# Foreign Keys
#
#  fk_rails_...  (department_id => departments.id)
#

class Area < ApplicationRecord
  belongs_to :department
  has_many :employees, -> {order(:id => :asc)}
end

app/controllers/web/areas_controller.rb
class Web::AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Departamentos", :web_departments_path
  add_breadcrumb "Áreas"

  def index
    @areas = Area.all
  end

  def new
    @area = Area.new
  end

  def show
    add_breadcrumb @area.name, web_area_path
  end

  def edit
  end

  def create
    @area = Area.create(area_params)
    if @area.save
      flash[:notice] = 'Area creada'
      redirect_to web_departments_path
    else
      render 'new'
    end
  end

  def update
    if @area.update(area_params)
      flash[:notice] = 'Departamento Actualizado'
      redirect_to web_departments_path
    else
      render 'edit'
    end
  end

  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to web_departments_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
  def set_area
    @area = Area.find_by_id(params[:id])
  end

  def area_params
    params.require(:area).permit(:name, :description, :department_id)
  end
end

app/helpers/web/areas_helper.rb
module Web::AreasHelper
end

app/views/web/areas/_form.html.erb
<div id="modal-cal" class="ui small modal">
  <div class="header">
    <%if @area.new_record? %>
      <h3><i class="save icon"></i> Nueva Área</h3>
    <% else %>
      <h3><i class="edit icon"></i> Área <%= @area.name %></h3>
    <% end %>
  </div>

  <div class="content">
    <%= form_for @area, url: url, method: method, html:{class: 'ui form error'} do |f| %>
    <div class="required field">
      <label for="area">Área:</label>
      <%= text_field(:area, :name, placeholder: 'Nombre del área') %>
    </div>
    <div class="field">
      <label for="description">Descripción:</label>
      <%=text_field(:area, :description, placeholder: 'Descripción del área') %>
    </div>
    <div class="required field">
      <label for="department">Departamento al que pertenece:</label>
      <%=f.collection_select(:department_id, Department.all, :id, :name, {:prompt => 'Seleccione...'}, {:class => 'ui fluid dropdown'}) %>
    </div>
    <div class="actions">
      <%= link_to 'Cancelar', web_departments_path, class: 'ui button' %>
      <%if @area.new_record? %>
        <%= f.submit 'Guardar', class: 'ui primary button' %>
      <% else %>
          <%= link_to 'Eliminar', web_area_path(@area), class: 'ui red button',method: :delete, data: { confirm: "¿Desea eliminar el área #{@area.name}?"} %>
          <%= f.submit 'Actualizar', class: 'ui primary button' %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/web/areas/_form.html.haml
= form_for @area, url: url, method: method, html:{class: 'ui form error'} do |f|
  .field
    =text_field(:area, :name, placeholder: 'Nombre del área')
  .field
    =text_field(:area, :description, placeholder: 'Descripción del área')
  .field
    =f.collection_select(:department_id, Department.all, :id, :name, {:prompt => 'Seleccione...'}, {:class => 'ui fluid dropdown'})
  .actions
    = link_to 'Cancelar', web_departments_path, class: 'ui button'
    -if @area.new_record?
      = f.submit 'Guardar', class: 'ui primary button'
    -else
      = f.submit 'Actualizar', class: 'ui primary button'

app/views/web/areas/edit.html.haml
= render partial: 'layouts/menutop'
= render partial: 'layouts/breadcrump'
- title "Editar área"
.ui.text.container
  %h1 Editar área #{@area.name}
  =render partial: 'form.html.haml', locals:{url:web_area_path(@area) ,method: 'PUT'}
  =@area.inspect

app/views/web/areas/edit.js.erb
$('<%= j render partial: "form", locals: {url: web_area_path(@area), method: "PUT"} %>').modal('show');

app/views/web/areas/index.html.haml
.ui.relaxed.divided.list
  -@areas.each do |f|
    .item
      %i.large.github.middle.aligned.icon
      .content
        .header
          = f.name
        .description
          = f.department.name

app/views/web/areas/new.html.haml
= render partial: 'layouts/menutop'
= render partial: 'layouts/breadcrump'
- title "Crear área"
.ui.text.container
  %h1 Nueva Área
  =render partial: 'form', locals: {url:web_areas_path, method: 'POST'}

app/views/web/areas/new.js.erb
$('<%= j render partial: "form", locals: {url: web_areas_path, method: 'POST'} %>').modal('show');

app/views/web/areas/show.html.haml
= render partial: 'layouts/menutop'
= render partial: 'layouts/breadcrump'
- title "Area #{@area.name}"

.ui.text.container
  %h4.ui.horizontal.divider.header Area
  %table.ui.definition.table
    %tbody
      %tr
        %td.three.wide.column ID. Área.
        %td= @area.id
      %tr
        %td Nombre
        %td= @area.name
      %tr
        %td Área
        %td= @area.description



  = link_to 'Regresar', web_departments_path, class: 'ui button'
  = link_to 'Editar', edit_web_area_path(@area), class: 'ui primary button'