config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
      sessions: 'authentication/sessions'
  }
  mount V2::Root => '/'
  devise_scope :user do
    authenticated :user do
      root 'main#home', as: :authenticated_root
      get 'calendarApp/', to: 'main#calendarApp' #ruta para el componente CalendarApp
      #Api Routes
      namespace :api do
        namespace :v1 do
          resources :users, only: [:index,:show, :create, :destroy, :update] # usuarios del sistema
          get 'list_shifts', to: 'list_shift#index'
          get 'list_departments', to: 'data_sets#index'
          get 'list_departments/:id', to: 'data_sets#show'
          get 'list_benefits', to: 'benefits#index'
          get 'list_benefits/:id', to: 'benefits#show'

        end
      end
      # web routes
      namespace :web do
        resources :contracts, :benefits, :departments, :shifts, :employees, :users, :areas, :calendars, :holidays
        get 'calendar_programmed_vs_real', to: 'calendar_trace#index'
        get 'kpi_productivity', to: 'calendar_trace#assistance'
        get 'update_holidays', to: 'holidays#refill', via: [:post]
      end
    end

  #Api Routes
  namespace :api do
      devise_for :users
    namespace :v1 do
      resources :calendars , param: :data
      resources :users, only: [:index,:show, :create, :destroy, :update] # usuarios del sistema
      get 'list_shifts', to: 'list_shift#index'
      get 'list_shifts/:time', to: 'list_shift#search_shift_type'
      get 'list_departments', to: 'data_sets#departments'
      get 'list_areas', to: 'data_sets#index'
      get 'list_areas/:id', to: 'data_sets#show'
      get 'list_benefits', to: 'benefits#index'
      get 'list_contracts', to: 'contracts#index'
      get 'list_benefits/:id', to: 'benefits#show'
      get 'List_calendars_code/:code', to: 'calendars#calendar_code'
      get 'list_calendar_logs', to: 'calendar_logs#index'
      get 'list_calendar_logs/:code', to: 'calendar_logs#show'
      get 'list_calendar_logs_dep/:department_id', to: 'calendar_logs#logs_dep'
      get 'list_calendar_logs_date/:date', to: 'calendar_logs#logs_date'
      get 'list_holidays', to: 'holidays#index'
      get 'list_holidays_year/:year', to: 'holidays#list_year'
      get 'list_holidays_month_year/:month/:year', to: 'holidays#list_month_year'
    end
  end
end

  # ========== Kit coding ========== #

  root 'main#home'
  get '*path' => 'main#err'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/web/calendar_trace_controller.rb
class Web::CalendarTraceController < ApplicationController
  add_breadcrumb "Home", :root_path

  def index
    add_breadcrumb "Seguimiento de asignaciones"
    @calendars = Calendar.current_week
    @employees = Employee.select(:id, :first_name, :last_name).includes(:calendars)
    @week = Calendar.select(:date).order(:date).distinct(:date).where('date >= ? and date <= ?', Date.today.beginning_of_week.strftime("%Y-%m-%d"),Date.today.at_end_of_week.strftime("%Y-%m-%d"))
  end

  def date
    @calendars = Calendar.last(7).includes(:shift)
    @employees.each do |e|
      e.calendars.last(7).each do |emca|
        @calendars.each do |cal|
          if emca.date = cal.date
            @test << emca
          end
        end
      end
    end
  end
  def real_status
    @date = Time.now
  end

  def assistance
    word = params[:keyword]
    Rails.logger.info "PARAMS: " + params.inspect + " ////////////////"
    if word
      @employees = Calendar.get_shifts_employees_per_month(word)
      Rails.logger.info "PARAMS @EMPLOYEE" + @employees.inspect
    else
      @employees = []
    end
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/web/calendar_trace_helper.rb
module Web::CalendarTraceHelper
end

app/views/web/calendar_trace/_employees.html.haml
-if @employees.any?
  =line_chart @employees, xtitle: "Cod. Turno", ytitle: "Número de asignaciones", download: true
-else
  .ui.inline.cookie.nag
    %span.title
      Empleado sin registro de turnos para los parametros solicitados.
    %i.close.icon

  :javascript
    $('.cookie.nag').nag('show');

app/views/web/calendar_trace/index.html.haml
= render partial: 'layouts/menutop'
= render partial: 'layouts/breadcrump'
- title "Turnos programados vs turnos reales"
.ui.container
  %strong.text.right #{Time.now.to_formatted_s(:short)}
  %table.ui.celled.table
    %thead
      %tr
        %th{:colspan => 8}
          %h3 Control Semana actual
      %tr
        %th.center.aligned Empleado
        %th.center.aligned Lunes
        %th.center.aligned Martes
        %th.center.aligned Miercoles
        %th.center.aligned Jueves
        %th.center.aligned Viernes
        %th.center.aligned Sabado
        %th.center.aligned Domingo
      %tbody
        -@employees.each do |employee|
          %tr
            %td= employee.full_name
            -if employee.calendars.any?
              -employee.calendars.current_week.preload(:shift).each do |calendar|
                %td.selectable.center.aligned
                  =link_to calendar.shift.cod, edit_web_calendar_path(calendar), remote: true
            -else
              %td{:class => 'center aligned warning'}
                %i.attention.icon
                  Empleado sin asignación de turnos para la última semana
  %hr
  %h2 Estadisticas turnos Febrero 2018 por Empleado
  .ui.form
    = form_tag '/web/kpi_productivity', method: :get, id: 'search_form', remote: true do
      .fields
        .field
          %lavel Metrica por trabajador:
          = select_tag :keyword, options_from_collection_for_select(@employees, :id, :full_name), class: 'ui selection dropdown', prompt: 'Seleccione empleado'
        .field.disabled
          = #text_field_tag(:keyword1, nil, placeholder: 'Mes', type: 'text')
      = content_tag :button, class: 'ui blue submit button', type: :submit do
        %i.search.icon
        Enviar
  %div#search
  %hr

  - contrario = Calendar.joins(:shift).select('calendars.id, calendars.date, shifts.time').last(7)
  = contrario.shift.time

  - roadmap = Calendar.joins(:employee, :shift).where(:first_name == 'catherine').select(:cod).group(:cod).count(:cod)

  %h2 Turnos asignados en Diciembre 2017
  =pie_chart Calendar.joins(:employee, :shift).select(:cod).group(:cod).count(:cod), width: '600px', height: '400px'
  %hr
  %h2 Turnos asignados Enero 2018
  -loca = Calendar.joins(:employee, :shift).where('extract(month from calendars.date) = ?', 1 ).where('employees.id' => 2).select(:cod).group(:cod).count(:cod)
  =area_chart loca

  %hr
  %h3 Turnos asignados en los tres últimos meses
  - var = Calendar.joins(:employee, :shift).select(:cod, :first_name).group(:first_name).group(:cod).count(:first_name)
  = line_chart var

app/views/web/calendar_trace/search.html.erb
<%= form_tag '/web/kpi_productivity', method: :get, id: 'search_form', remote: true do %>
  <div class="field">
    <%= text_field_tag(:keyword, nil, placeholder: 'id') %>
  </div>
  <%= content_tag :button, class: 'ui primary button', type: :submit do %>
      Enviar
  <% end %>
<% end %>
<div id="search">
</div>